### ISSUE TITLE
Add format to text messages

### ISSUE THREAD

**Issue by exos** [botmasters/ircgrampp#12]
Telegram admits markdown format to messages, see [parse_mode](https://core.telegram.org/bots/api#sendmessage) and [this](https://core.telegram.org/bots/api#markdown-style).

The goal is the irc -> telegram messages have an style to visually separate the user to the message:

for example:

> [IRC/zephrax] tenés código sin pushear?

Can be

> **<zephrax**> tenés código sin pushear?

or

> *_irc_ **<zephrax**> tenés código sin pushear?

**Comment by segmentati0nf4ult** [comment]
I've added some formatting to messages. @exos please check those changes and close this issue if you agree.

**Comment by exos** [comment]
Don't escape mardown from irc:

```
exos | escapa *escapa* _escapa_ ~escapa~ [escapa](http://google.com) ?
```

To:

![screen](http://esfriki.com/f/Screenshot_20170420_030311.png)

**Comment by exos** [comment]
Don't escape mardown from irc:

```
exos | escapa *escapa* _escapa_ ~escapa~ [escapa](http://google.com) ?
```

To:

![screen](http://esfriki.com/f/Screenshot_20170420_030311.png)

**Comment by exos** [comment]
Close as resolved, there are a bug related:

https://github.com/botmasters/ircgrampp/issues/20
