### ISSUE TITLE
username undefined if telegram user has not username

### ISSUE THREAD

**Issue by carpe-diem** [botmasters/ircgrampp#16]
If telegram user not define his username, when he writes appear undefine in the irc.

`[Telegram/@undefined]`

**Comment by carpe-diem** [comment]
In this case, we can use first_name. 
What do you think ?

**Comment by exos** [comment]
There are an user without username to test it?

**Comment by exos** [comment]
Fix

0.1.0: 44ac4d5
next: ab3c259
