### ISSUE TITLE
Add support for nickserv identifying

### ISSUE THREAD

**Issue by segmentati0nf4ult** [botmasters/ircgrampp#8]
It would be good to implement this functionality.

1) Configure nickserv identification
2) Configure modes for channel?
3) Configure modes for users created by the bot?

**Comment by exos** [comment]
Currently I'm working in the plugins integration, finished that, I want to integrate the service bots (NickServ, ChanServ, etc), in one plugin to keep the core lightweight..

**Comment by exos** [comment]
Resolved as plugin: https://github.com/botmasters/ircgrampp-plugin-nickserv
